<?php

/**
 * Account Detail
 * Sirim Demo Account API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ksamsudi@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace App\Http\Controllers;
use App\Account;

// use Illuminate\Support\Facades\Request;
use Illuminate\Http\Request;

class ApiController extends Controller
{
    /**
     * Constructor
     */
    // public function __construct()
    // {
    // }

    /**
     * Operation getAccounts
     *
     * Sirim demo.
     *
     *
     * @return Http response
     */
    public function getAccounts()
    {
    $accounts = Account::get()->toJson(JSON_PRETTY_PRINT);
      return response($accounts, 200);
    }
    /**
     * Operation putAccountsNric
     *
     * .
     *
     * @param string $nric Person NRIC (required)
     *
     * @return Http response
     */
    public function putAccountsNric($nric)
    {
        $input = Request::all();

        //path params validation

        //not path params validation

        return response('How about implementing putAccountsNric as a put method ?');
    }
     /**
     * Operation getPing
     *
     * .
     *
     * @return Http response
     */
    public function getPing()
    {
	    date_default_timezone_set("Asia/Kuala_Lumpur");
      	$ping = "Ping@ " .date("d M Y") . "  " .date("H:i:s");
      	return response($ping, 200);
    }
}
